version: '3.3'

services:
  web:
    build: .
    working_dir: /usr/src/sh-www/sh/
    command: python main.py
    volumes:
      - .:/usr/src/sh-www/
    ports:
      - 5001:5001
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sh
      - POSTGRES_PASSWORD=hellogoodbye
      - POSTGRES_DB=sh

volumes:
  postgres_data:
